language: rust

rust:
  - nightly

before_script:
  - (cargo install mdbook --version =0.1.7)

script: 
  - export PATH=$PATH:/home/travis/.cargo/bin && mdbook test
  - cd stable-check && cargo run -- ../src
