language: rust

rust:
  - nightly

before_script:
  - (cargo install mdbook --git https://github.com/rust-lang-nursery/mdBook.git --force || true)

script: 
  - export PATH=$PATH:/home/travis/.cargo/bin && mdbook test
  - cd stable-check && cargo run -- ../src
