[package]
name = "core_arch"
version = "0.1.3"
authors = [
    "Alex Crichton <alex@alexcrichton.com>",
    "Andrew Gallant <jamslam@gmail.com>",
    "Gonzalo Brito Gadeschi <gonzalobg88@gmail.com>",
]
description = "`core::arch` - Rust's core library architecture-specific intrinsics."
documentation = "https://docs.rs/core_arch"
homepage = "https://github.com/rust-lang-nursery/stdsimd"
repository = "https://github.com/rust-lang-nursery/stdsimd"
readme = "README.md"
keywords = ["core", "simd", "arch", "intrinsics"]
categories = ["hardware-support", "no-std"]
license = "MIT/Apache-2.0"
build = "build.rs"

[badges]
travis-ci = { repository = "rust-lang-nursery/stdsimd" }
appveyor = { repository = "rust-lang-nursery/stdsimd"  }
is-it-maintained-issue-resolution = { repository = "rust-lang-nursery/stdsimd" }
is-it-maintained-open-issues = { repository = "rust-lang-nursery/stdsimd" }
maintenance = { status = "experimental" }

[dev-dependencies]
stdsimd-test = { version = "0.*", path = "../stdsimd-test" }
std_detect = { version = "0.*", path = "../std_detect" }

[target.wasm32-unknown-unknown.dev-dependencies]
wasm-bindgen-test = "=0.2.19"

[package.metadata.docs.rs]
rustdoc-args = [ "--cfg", "dox" ]