[package]
name = "rls"
version = "0.1.0"
authors = ["Jonathan Turner <jturner@mozilla.com>"]

[dependencies]
cargo = { git = "https://github.com/rust-lang/cargo" }
derive-new = "0.3"
env_logger = "0.3"
languageserver-types = { git = "https://github.com/gluon-lang/languageserver-types" }
log = "0.3"
racer = { git = "https://github.com/phildawes/racer" }
rls-analysis = { git = "https://github.com/nrc/rls-analysis" }
rls-data = "0.1"
rls-span = { version = "0.1", features = ["serialize-serde"] }
rls-vfs = { git = "https://github.com/nrc/rls-vfs", features = ["racer-impls"] }
rustc-serialize = "0.3"
rustfmt = { git = "https://github.com/rust-lang-nursery/rustfmt" }
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
toml = "0.3"
url = "1.1.0"
url_serde = "0.1.0"

[dependencies.hyper]
version = "0.9"
default-features = false
