language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=aarch64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET=i686-unknown-linux-gnu
      rust: nightly
    - env: TARGET=mips-unknown-linux-gnu
      rust: nightly
    - env: TARGET=mips64-unknown-linux-gnuabi64
      rust: nightly
    - env: TARGET=mips64el-unknown-linux-gnuabi64
      rust: nightly
    - env: TARGET=mipsel-unknown-linux-gnu
      rust: nightly
    - env: TARGET=powerpc-unknown-linux-gnu
      rust: nightly
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=powerpc64le-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=cargo-fmt
      rust: beta

    - env: TARGET=wasm32-unknown-unknown
      rust: nightly
      install: rustup target add $TARGET
      script:
        - cargo build --target $TARGET
        - cargo build --no-default-features --target $TARGET

before_install: set -e

install:
  - bash ci/install.sh

script:
  - export PATH=$HOME/.local/bin:$PATH
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - staging
    - trying
