[package]
name = "assert-instr-macro"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
proc-macro = true
test = false

[dependencies]
proc-macro2 = { version = "0.2", features = ["nightly"] }
quote = "0.4"
syn = { version = "0.12", features = ["full"] }
