[package]
name = "assert-instr-macro"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
proc-macro = true
test = false

[dependencies]
proc-macro2 = { version = "0.3", features = ["nightly"] }
quote = "0.5"
syn = { version = "0.13", features = ["full"] }
