environment:
    global:
        PROJECT_NAME: miri
    matrix:
        - TARGET: i686-pc-windows-msvc
          MSYS2_BITS: 32
        - TARGET: x86_64-pc-windows-msvc
          MSYS2_BITS: 64

install:
    - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain nightly
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\Users\appveyor\.rustup\toolchains\nightly-%TARGET%\bin
    - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
    - rustc -V
    - cargo -V
    - rustup component add rust-src
    - cargo install --git https://github.com/japaric/xargo.git
    - cd xargo
    - set RUSTFLAGS=-Zalways-encode-mir -Zmir-emit-validate=1
    - xargo build
    - set RUSTFLAGS=
    - cd ..

build: false

test_script:
    - set RUST_BACKTRACE=1
    - cargo build --locked --release
    - cargo test --locked --release

notifications:
    - provider: Email
      on_build_success: false
