[package]
authors = ["Scott Olson <scott@solson.me>"]
description = "An experimental interpreter for Rust MIR."
license = "MIT/Apache-2.0"
name = "miri"
repository = "https://github.com/solson/miri"
version = "0.1.0"
build = "build.rs"

[[bin]]
doc = false
name = "miri"
path = "miri/bin/miri.rs"

[[bin]]
doc = false
name = "cargo-miri"
path = "miri/bin/cargo-miri.rs"
required-features = ["cargo_miri"]

[lib]
path = "miri/lib.rs"

[dependencies]
byteorder = { version = "1.1", features = ["i128"]}
env_logger = "0.4.3"
log = "0.3.6"
log_settings = "0.1.1"
cargo_metadata = { version = "0.2", optional = true }
rustc_miri = { path = "src/librustc_mir" }

[features]
cargo_miri = ["cargo_metadata"]

[dev-dependencies]
compiletest_rs = { version = "0.2.10", features = ["tmp"] }

[workspace]
exclude = ["xargo", "cargo-miri-test", "rustc_tests"]
