[book]
title = "Guide to Rustc Development"
author = "Rustc developers"
description = "A guide to developing rustc"

[output.html]

[output.html.search]

[output.linkcheck]
follow-web-links = true
exclude = [ "crates\\.io", "gcc\\.godbolt\\.org" ]
