sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - beta # Change this to stable when Rust 1.31.0 is out
branches:
  only:
  - master
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_script:
  - (cargo install mdbook --vers 0.1.7 --force || true)
script:
  - bash ci/build.sh
