sudo: false
language: rust
cache: cargo
rust:
  - nightly
branches:
  only:
  - master
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_script:
  - (cargo install mdbook --git https://github.com/azerupi/mdBook.git --force || true)
script:
  - bash ci/build.sh
