environment:
  # We don't want to do identical comdat folding as it messes up the ability to
  # generate lossless backtraces in some cases. This is enabled by rustc by
  # default so pass a flag to disable it to ensure our tests work ok.
  RUSTFLAGS: -Clink-args=/OPT:NOICF

  matrix:
  - TARGET: x86_64-pc-windows-msvc

install:
  # Install rust, x86_64-pc-windows-msvc host
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain nightly-2018-10-20
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - C:\msys64\usr\bin\sh ci\run.sh

branches:
  only:
    - master
