[package]
name = "stdsimd-test"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
assert-instr-macro = { path = "../assert-instr-macro" }
simd-test-macro = { path = "../simd-test-macro" }
backtrace = "0.3"
cc = "1.0"
lazy_static = "1.0"
rustc-demangle = "0.1.8"
