[package]
authors = ["Scott Olson <scott@solson.me>"]
description = "An experimental interpreter for Rust MIR."
license = "MIT/Apache-2.0"
name = "rustc_miri"
repository = "https://github.com/solson/miri"
version = "0.1.0"
workspace = "../.."

[lib]
path = "lib.rs"

[dependencies]
byteorder = { version = "1.1", features = ["i128"]}
log = "0.3.6"
log_settings = "0.1.1"
lazy_static = "0.2.8"
regex = "0.2.2"
backtrace = "0.3.3"
