[package]
name = "stdsimd-verify"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
proc-macro2 = { version = "0.2", features = ["nightly"] }
quote = "0.4"
syn = { version = "0.12", features = ["full"] }

[lib]
proc-macro = true
test = false

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.2"
